name: 'TESTAR Scriptless Testing (Windows)'
description: 'Runs TESTAR with configurable parameters for web applications'
inputs:
  version:
    description: 'TESTAR version (e.g. v2.6.37)'
    required: false
    default: 'v2.6.37'
  application_name:
    description: 'Name of the SUT being tested by TESTAR (for report identification)'
    required: false
    default: 'SUT_webdriver_generic'
  sut:
    description: 'Web URL of the SUT to be tested by TESTAR'
    required: true
  sequences:
    description: 'Number of sequences'
    required: false
    default: '5'
  sequence_length:
    description: 'Length of each sequence'
    required: false
    default: '10'
  suspicious_titles:
    description: 'Regex for suspicious titles'
    required: false
    default: '.[eE]rror.|.[eE]xcep[ct]ion.'

runs:
  using: 'composite'
  steps:
    - name: Download and unzip TESTAR
      shell: pwsh
      run: |
        $url = "https://github.com/TESTARtool/TESTAR_dev/releases/download/${{ inputs.version }}/testar_${{ inputs.version }}_java11.zip"
        Invoke-WebRequest -Uri $url -OutFile "testar_release.zip"
        Expand-Archive -Path "testar_release.zip" -DestinationPath "testar_release"

    - name: Run TESTAR
      shell: pwsh
      run: |
        $testarPath = "testar_release\testar\bin"
        Set-Location $testarPath
        .\testar.bat `
          sse=webdriver_generic `
          WebDomainsAllowed=null `
          WebPathsAllowed=null `
          ShowVisualSettingsDialogOnStartup=false `
          FlashFeedback=false `
          AlwaysCompile=true `
          Mode=Generate `
          ApplicationName='"${{ inputs.application_name }}"' `
          SUTConnectorValue='" ""C:\\SeleniumWebDrivers\\ChromeDriver\\chromedriver.exe"" ""${{ inputs.sut }}"" "' `
          Sequences=${{ inputs.sequences }} `
          SequenceLength=${{ inputs.sequence_length }} `
          SuspiciousTitles='"${{ inputs.suspicious_titles }}"'

    - name: Upload TESTAR output results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: testar-output-results
        path: testar_release/testar/bin/output
