name: Test TESTAR Action (webdriver_generic)

on:
  push:
    branches: [ windows ]
  workflow_dispatch:

jobs:
  testar-web:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Run TESTAR Action (webdriver_generic)
        uses: ./ # Local ferpasri/TESTAR_Action
        with:
          application_name: 'parabank'
          sut: 'https://para.testar.org/parabank'
          sequences: '3'
          sequence_length: '5'
          suspicious_titles: '.[eE]rror.|.[eE]xcep[ct]ion.|.[iI]nvalid.'
